# Generated by Django 6.0.1 on 2026-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='online_paym_hub_id_058cf8_idx',
            old_name='online_pay_hub_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='online_paym_hub_id_8af41e_idx',
            old_name='online_pay_hub_id_source_idx',
        ),
    ]
